version: '3.9'

services:
  backend:
    image: aamadeo/pm-api:latest
    container_name: backend
    expose:
      - 3000:3000
    networks:
      - app_network
    environment:
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    image: aamadeo/pm-ui:latest
    container_name: frontend
    expose:
      - 80:3000
    environment:
      - API_BASEURL=${API_BASEURL}
    networks:
      - app_network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./ssl:/etc/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge